### PR TITLE
bump to 5.1.1

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
This is required to build `dgl` but blocked by https://github.com/KarypisLab/METIS/issues/13. We need a git tag from upstream.

It is also blocked by https://github.com/conda-forge/staged-recipes/pull/12547

**Comment by hadim** [comment]
The build works but I get a weird glibc error during testing: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=208979&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=995

**Comment by hadim** [comment]
@SylvainCorlay @basnijholt one of you wants to review this?

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@hadim, many tests are still failing.

**Comment by hadim** [comment]
Yes with a glibc error similar to this:

```
7f10252b2000-7f10252b3000 rw-p 00094000 08:01 3120629                    /home/conda/feedstock_root/build_artifacts/metis_1600041346401/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libmetis.so
7f10252b3000-7f10252b5000 rw-p 00000000 00:00 0 
7f10252b5000-7f10252b6000 r--p 00020000 08:01 2090911                    /lib64/ld-2.12.so
7f10252b6000-7f10252b7000 rw-p 00021000 08:01 2090911                    /lib64/ld-2.12.so
7f10252b7000-7f10252b8000 rw-p 00000000 00:00 0 
7ffe7b8ee000-7ffe7b910000 rw-p 00000000 00:00 0                          [stack]
7ffe7b94f000-7ffe7b952000 r--p 00000000 00:00 0                          [vvar]
7ffe7b952000-7ffe7b954000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
*** glibc detected *** gpmetis: munmap_chunk(): invalid pointer: 0x00005595871650d0 **
```

I don't really get what is happening.

**Comment by basnijholt** [comment]
Unfortunately, I don't have time to look into this right now.

**Comment by hadim** [comment]
all good @basnijholt.

Let's let this open and hopefully someone will come with a fix. I'll try to investigate if I can find some time.

**Comment by SimonBoothroyd** [comment]
@hadim it looks like the main author added a couple of commits patching memory issues (https://github.com/KarypisLab/METIS/commit/38a8fb0fd1cdde963b04997c7be844028602793a, https://github.com/KarypisLab/METIS/commit/36262adecaa9720a4417a67124428061c367fd3f) - patching 5.1.1 with these changes seems to resolve the segfault when building and testing with `build-locally`. 

So it might require a new release with the patches included to resolve this?

**Comment by hadim** [comment]
> So it might require a new release with the patches included to resolve this?

Yes a new release is required indeed. That being said you can test the new commits in that PR or another one if you wish.

**Comment by hadim** [comment]
@SimonBoothroyd do you want to open an new issue upstream to ask for a new release?

**Comment by SimonBoothroyd** [comment]
@hadim I'd be happy to. I'm currently just looking into the windows build failures in https://github.com/conda-forge/staged-recipes/pull/12547 but will follow up after I've finished with that.

**Comment by SimonBoothroyd** [comment]
We may also need to enable these flags to make sure things work correctly with dgl: https://github.com/dmlc/dgl/blob/9a7235faf2835d424c4587e703024248e6b9f465/CMakeLists.txt#L121-L128

**Comment by hadim** [comment]
@SimonBoothroyd after https://github.com/conda-forge/staged-recipes/pull/12547 is merged can I let you take over this PR (or create a new one based on this one maybe).

My bandwidth will be very limited to keep working on a dgl conda package.

**Comment by SimonBoothroyd** [comment]
Sure that sounds good with me.

**Comment by hadim** [comment]
Thanks! And I would be happy to review/test things if you need.

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by SimonBoothroyd** [comment]
It seems a new tagged version is now available that hopefully won't segfault...https://github.com/KarypisLab/METIS/releases/tag/v5.2.1

Not sure if DGL is compatible with this however... there were some pretty big changes IIRC but I can't remember if those included API breaks..

**Comment by mikemhenry** [comment]
@SimonBoothroyd That is what I am worried about, maybe we can get lucky with a patch for DGL if it is simple...

**Comment by hadim** [comment]
closing in favour of #32

**Pull request closed without merging**
