### PR TITLE
Add regression test for upstream issue 69

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/KarypisLab/METIS/issues/69 and https://github.com/conda-forge/metis-feedstock/issues/35 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
```
metis_test.cpp:9:11: fatal error: metis.h: No such file or directory
    9 | # include <metis.h>
```

I don't have an example handy, but you will likely need to pass in CMAKE args or something when building these tests so it can find the headers.

**Comment by mikemhenry** [comment]
Looks like the test is passing (at least on linux, I think the issue on OSX is with the source file/clang is unhappy), I am not opposed to including it in the feedstock (it is fast and it is a nice check we can link to it) but can you track down the license for it?

**Comment by mikemhenry** [comment]
:upside_down_face: sorry about missing that, I just saw the comment on the top of the file and when I skimmed it, missed the note about the license.

**Pull request closed without merging**
