### PR TITLE
Enable build on Windows and ppc64le

### PR DESCRIPTION
**Pull request by traversaro**
To unblock the situation in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4857 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
ppc64le failure log is not clear:
~~~
make[1]: Entering directory '$SRC_DIR/build'
$BUILD_PREFIX/bin/cmake -S$SRC_DIR -B$SRC_DIR/build --check-build-system CMakeFiles/Makefile.cmake 0
$BUILD_PREFIX/bin/cmake -E cmake_progress_start $SRC_DIR/build/CMakeFiles $SRC_DIR/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[2]: Entering directory '$SRC_DIR/build'
make  -f libmetis/CMakeFiles/metis.dir/build.make libmetis/CMakeFiles/metis.dir/depend
make[3]: Entering directory '$SRC_DIR/build'
cd $SRC_DIR/build && $BUILD_PREFIX/bin/cmake -E cmake_depends "Unix Makefiles" $SRC_DIR $SRC_DIR/libmetis $SRC_DIR/build $SRC_DIR/build/libmetis $SRC_DIR/build/libmetis/CMakeFiles/metis.dir/DependInfo.cmake "--color="
make[3]: Leaving directory '$SRC_DIR/build'
make  -f libmetis/CMakeFiles/metis.dir/build.make libmetis/CMakeFiles/metis.dir/build
make[3]: Entering directory '$SRC_DIR/build'
[  1%] Building C object libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o
cd $SRC_DIR/build/libmetis && $BUILD_PREFIX/bin/powerpc64le-conda-linux-gnu-cc -Dmetis_EXPORTS -I$SRC_DIR/GKlib -I$SRC_DIR/build/xinclude -I$SRC_DIR/libmetis/. -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/metis-5.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -DLINUX -D_FILE_OFFSET_BITS=64 -std=c99 -fno-strict-aliasing -march=native -fPIC -Werror -Wall -pedantic -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unknown-pragmas -Wno-unused-label -DNDEBUG -DNDEBUG2 -DHAVE_EXECINFO_H -DHAVE_GETLINE -O3 -fPIC -MD -MT libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o -MF CMakeFiles/metis.dir/__/GKlib/b64.c.o.d -o CMakeFiles/metis.dir/__/GKlib/b64.c.o -c $SRC_DIR/GKlib/b64.c
make[3]: Leaving directory '$SRC_DIR/build'
make[2]: Leaving directory '$SRC_DIR/build'
make[1]: Leaving directory '$SRC_DIR/build'
travis_time:end:0090c1c1:start=1698698356007758298,finish=1698698641656487711,duration=285648729413,event=script
[0K[31;1mThe command "if [[ ${PLATFORM} =~ .*linux.* ]]; then CONDA_FORGE_DOCKER_RUN_ARGS="--network=host --security-opt=seccomp=unconfined" ./.scripts/run_docker_build.sh; fi" exited with 1.[0m


Done. Your build exited with 1.
~~~

perhaps out of memory error?

**Comment by traversaro** [comment]
Windows fails with a CMake config error:
~~~
-- Looking for getline - not found
-- checking for thread-local storage - not found
CMake Error at CMakeLists.txt:43 (add_subdirectory):
  add_subdirectory given source "build/xinclude" which is not an existing
  directory.


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "C:\Miniforge\Scripts\conda-mambabuild-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 228, in call_conda_build
~~~

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> Windows fails with a CMake config error:
> 
> ```
> -- Looking for getline - not found
> -- checking for thread-local storage - not found
> CMake Error at CMakeLists.txt:43 (add_subdirectory):
>   add_subdirectory given source "build/xinclude" which is not an existing
>   directory.
> 
> 
> -- Configuring incomplete, errors occurred!
> Traceback (most recent call last):
>   File "C:\Miniforge\Scripts\conda-mambabuild-script.py", line 9, in <module>
>     sys.exit(main())
>   File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 256, in main
>     call_conda_build(action, config)
>   File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 228, in call_conda_build
> ```

Probably we need to do the steps done in https://github.com/KarypisLab/METIS/blob/v5.1.1-DistDGL-v0.5/vsgen.bat#L3 .

**Comment by traversaro** [comment]
New Windows failure:
~~~
2023-10-30T21:03:54.2511600Z cl : Command line warning D9002 : ignoring unknown option '-O3'
2023-10-30T21:03:54.2518703Z auxapi.c
2023-10-30T21:03:54.6628693Z C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_math.h(88): warning C4005: 'INFINITY': macro redefinition
2023-10-30T21:03:54.6631309Z %SRC_DIR%\GKlib\gk_arch.h(65): note: see previous definition of 'INFINITY'
2023-10-30T21:03:54.6946239Z %SRC_DIR%\build\xinclude\metis.h(115): fatal error C1189: #error:  "Incorrect user-supplied value fo IDXTYPEWIDTH"
2023-10-30T21:03:54.7117350Z NMAKE : fatal error U1077: 'D:\bld\metis_1698699544729\_build_env\Library\bin\cmake.exe' : return code '0x2'
2023-10-30T21:03:54.7120199Z Stop.
2023-10-30T21:03:54.7189956Z NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
2023-10-30T21:03:54.7191808Z Stop.
2023-10-30T21:03:54.7220317Z NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
2023-10-30T21:03:54.7222966Z Stop.
~~~

Probably we need to do what is described in https://github.com/KarypisLab/METIS/blob/v5.1.1-DistDGL-v0.5/BUILD-Windows.txt#L25 .

**Comment by traversaro** [comment]
> perhaps out of memory error?

Actually I did not read correctly, the error is that in the compiler invocation `-march=native` is used:
~~~
cd $SRC_DIR/build/libmetis && $BUILD_PREFIX/bin/powerpc64le-conda-linux-gnu-cc -Dmetis_EXPORTS -I$SRC_DIR/GKlib -I$SRC_DIR/build/xinclude -I$SRC_DIR/libmetis/. -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/metis-5.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -DLINUX -D_FILE_OFFSET_BITS=64 -std=c99 -fno-strict-aliasing -march=native -fPIC -Werror -Wall -pedantic -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unknown-pragmas -Wno-unused-label -DNDEBUG -DNDEBUG2 -DHAVE_EXECINFO_H -DHAVE_GETLINE -O3 -fPIC -MD -MT libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o -MF CMakeFiles/metis.dir/__/GKlib/b64.c.o.d -o CMakeFiles/metis.dir/__/GKlib/b64.c.o -c $SRC_DIR/GKlib/b64.c
~~~

This specific problem was fixed by https://github.com/KarypisLab/GKlib/pull/22 . However, the problem is that no conda-forge build should actually use `-march=native`. So we should patch it out.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge/metis the PR is ready for review.

**Comment by mikemhenry** [comment]
Awesome, thanks for this!

**Pull request merged**
